/* ============================================================
   SOLARIS — Heliometric Intelligence Platform
   cabal_macros.h
   Auto-generated by Cabal — DO NOT EDIT MANUALLY
   GHC 9.6.7 | Cabal 3.10 | base 4.18.3.0
   ============================================================ */

#ifndef CABAL_MACROS_H
#define CABAL_MACROS_H

/* ── solar-server ─────────────────────────────────────────── */
#ifndef VERSION_solar_server
#define VERSION_solar_server "0.1.0.0"
#endif

#ifndef MIN_VERSION_solar_server
#define MIN_VERSION_solar_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif

/* ── base ─────────────────────────────────────────────────── */
#ifndef VERSION_base
#define VERSION_base "4.18.3.0"
#endif

#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 3)
#endif

/* ── warp (HTTP server) ───────────────────────────────────── */
#ifndef VERSION_warp
#define VERSION_warp "3.3.30"
#endif

#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 30)
#endif

/* ── aeson (JSON) ─────────────────────────────────────────── */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.1.0"
#endif

#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 1)
#endif

/* ── stm ──────────────────────────────────────────────────── */
#ifndef VERSION_stm
#define VERSION_stm "2.5.3.0"
#endif

#ifndef MIN_VERSION_stm
#define MIN_VERSION_stm(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 3)
#endif

/* ── async ────────────────────────────────────────────────── */
#ifndef VERSION_async
#define VERSION_async "2.2.5"
#endif

#ifndef MIN_VERSION_async
#define MIN_VERSION_async(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 5)
#endif

/* ── conduit (streaming) ──────────────────────────────────── */
#ifndef VERSION_conduit
#define VERSION_conduit "1.3.5"
#endif

#ifndef MIN_VERSION_conduit
#define MIN_VERSION_conduit(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 5)
#endif

/* ── text ─────────────────────────────────────────────────── */
#ifndef VERSION_text
#define VERSION_text "2.0.2"
#endif

#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif

/* ── time ─────────────────────────────────────────────────── */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif

#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif

/* ── scientific (numeric) ─────────────────────────────────── */
#ifndef VERSION_scientific
#define VERSION_scientific "0.3.7.0"
#endif

#ifndef MIN_VERSION_scientific
#define MIN_VERSION_scientific(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 7)
#endif

/* ── Tool versions ────────────────────────────────────────── */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.7"
#endif

#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 7)
#endif

#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.7"
#endif

#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif

#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif

#ifndef TOOL_VERSION_cabal
#define TOOL_VERSION_cabal "3.10.3.0"
#endif

/* ── Component / Package identity ────────────────────────── */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "solar-server-0.1.0.0-inplace-solar-server"
#endif

#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "solar-server-0.1.0.0"
#endif

#endif /* CABAL_MACROS_H */
